image: node:10.16.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@10.1.4
  - npm install
  - ng build
  - mv dist/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages